export interface Recipe {
  id: string
  title: string
  description: string
  image: string
  rating: number
  prepTime: string
  cookTime: string
  tags: string[]
  ingredients: string[]
  instructions: string[]
  authorId: string
  authorName: string
}

export const recipes: Recipe[] = [
  {
    id: "1",
    title: "Classic Chocolate Chip Cookies",
    description: "Soft and chewy chocolate chip cookies with a perfect golden edge.",
    image: "/placeholder.svg?height=300&width=400",
    rating: 4.8,
    prepTime: "15 mins",
    cookTime: "10 mins",
    tags: ["Dessert", "Baking", "Cookies", "Chocolate"],
    ingredients: [
      "2 1/4 cups all-purpose flour",
      "1 teaspoon baking soda",
      "1 teaspoon salt",
      "1 cup unsalted butter, softened",
      "3/4 cup granulated sugar",
      "3/4 cup packed brown sugar",
      "2 large eggs",
      "2 teaspoons vanilla extract",
      "2 cups semi-sweet chocolate chips",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "Combine flour, baking soda, and salt in a small bowl.",
      "Beat butter, granulated sugar, and brown sugar in a large mixer bowl.",
      "Add eggs one at a time, beating well after each addition. Beat in vanilla.",
      "Gradually beat in flour mixture. Stir in chocolate chips.",
      "Drop by rounded tablespoon onto ungreased baking sheets.",
      "Bake for 9 to 11 minutes or until golden brown.",
      "Cool on baking sheets for 2 minutes; remove to wire racks to cool completely.",
    ],
    authorId: "user_1",
    authorName: "Julia Chen",
  },
  {
    id: "2",
    title: "Creamy Garlic Parmesan Pasta",
    description: "A quick and delicious pasta dish with a creamy garlic parmesan sauce.",
    image: "/placeholder.svg?height=300&width=400",
    rating: 4.5,
    prepTime: "5 mins",
    cookTime: "15 mins",
    tags: ["Pasta", "Italian", "Quick Meals", "Vegetarian"],
    ingredients: [
      "8 oz fettuccine pasta",
      "2 tablespoons butter",
      "4 cloves garlic, minced",
      "1 cup heavy cream",
      "1 cup grated Parmesan cheese",
      "Salt and pepper to taste",
      "Fresh parsley, chopped (for garnish)",
    ],
    instructions: [
      "Cook pasta according to package directions. Drain and set aside.",
      "In a large skillet, melt butter over medium heat.",
      "Add minced garlic and sauté for 1-2 minutes until fragrant.",
      "Pour in heavy cream and bring to a simmer.",
      "Reduce heat to low and stir in Parmesan cheese until melted and smooth.",
      "Season with salt and pepper to taste.",
      "Add cooked pasta to the sauce and toss until well coated.",
      "Garnish with fresh parsley before serving.",
    ],
    authorId: "user_2",
    authorName: "Marco Rossi",
  },
  {
    id: "3",
    title: "Avocado Toast with Poached Egg",
    description: "A nutritious breakfast featuring creamy avocado and perfectly poached eggs.",
    image: "/placeholder.svg?height=300&width=400",
    rating: 4.2,
    prepTime: "10 mins",
    cookTime: "5 mins",
    tags: ["Breakfast", "Healthy", "Quick", "Vegetarian"],
    ingredients: [
      "2 slices whole grain bread",
      "1 ripe avocado",
      "2 eggs",
      "1 tablespoon white vinegar",
      "Salt and pepper to taste",
      "Red pepper flakes (optional)",
      "Fresh herbs (optional)",
    ],
    instructions: [
      "Toast the bread slices until golden brown.",
      "Cut the avocado in half, remove the pit, and scoop the flesh into a bowl.",
      "Mash the avocado with a fork and season with salt and pepper.",
      "Spread the mashed avocado evenly on the toast slices.",
      "Fill a saucepan with water (about 3 inches deep) and bring to a gentle simmer.",
      "Add vinegar to the water.",
      "Crack each egg into a small bowl, then gently slide into the simmering water.",
      "Cook for 3-4 minutes for a runny yolk.",
      "Remove eggs with a slotted spoon and place on top of the avocado toast.",
      "Season with salt, pepper, and optional red pepper flakes or herbs.",
    ],
    authorId: "user_3",
    authorName: "Emma Wilson",
  },
  {
    id: "4",
    title: "Homemade Margherita Pizza",
    description: "A classic Italian pizza with fresh tomatoes, mozzarella, and basil.",
    image: "/placeholder.svg?height=300&width=400",
    rating: 4.9,
    prepTime: "30 mins",
    cookTime: "15 mins",
    tags: ["Italian", "Pizza", "Vegetarian", "Dinner"],
    ingredients: [
      "1 pizza dough (homemade or store-bought)",
      "1/4 cup tomato sauce",
      "8 oz fresh mozzarella cheese, sliced",
      "2 tomatoes, sliced",
      "Fresh basil leaves",
      "2 tablespoons olive oil",
      "Salt and pepper to taste",
      "1 teaspoon dried oregano (optional)",
    ],
    instructions: [
      "Preheat oven to 475°F (245°C) with a pizza stone if available.",
      "Roll out the pizza dough on a floured surface to your desired thickness.",
      "Transfer the dough to a pizza peel or baking sheet lined with parchment paper.",
      "Spread tomato sauce evenly over the dough, leaving a small border for the crust.",
      "Arrange mozzarella slices and tomato slices on top.",
      "Drizzle with olive oil and season with salt, pepper, and oregano if using.",
      "Bake for 12-15 minutes until the crust is golden and the cheese is bubbly.",
      "Remove from oven and immediately top with fresh basil leaves.",
      "Let cool slightly before slicing and serving.",
    ],
    authorId: "user_2",
    authorName: "Marco Rossi",
  },
  {
    id: "5",
    title: "Spicy Thai Coconut Soup",
    description: "A fragrant and spicy Thai soup with coconut milk, lemongrass, and fresh herbs.",
    image: "/placeholder.svg?height=300&width=400",
    rating: 4.7,
    prepTime: "20 mins",
    cookTime: "25 mins",
    tags: ["Thai", "Soup", "Spicy", "Asian"],
    ingredients: [
      "2 cans (14 oz each) coconut milk",
      "2 cups chicken or vegetable broth",
      "2 stalks lemongrass, bruised and cut into 2-inch pieces",
      "4 slices fresh ginger",
      "3 cloves garlic, crushed",
      "2 Thai chili peppers, sliced (adjust to taste)",
      "2 tablespoons fish sauce (or soy sauce for vegetarian)",
      "1 tablespoon brown sugar",
      "1 lime, juiced",
      "1 lb shrimp or tofu cubes",
      "1 cup mushrooms, sliced",
      "Fresh cilantro and green onions for garnish",
    ],
    instructions: [
      "In a large pot, combine coconut milk and broth over medium heat.",
      "Add lemongrass, ginger, garlic, and chili peppers. Bring to a simmer.",
      "Simmer for 10 minutes to infuse the flavors.",
      "Add fish sauce and brown sugar, stirring until dissolved.",
      "Add mushrooms and cook for 3 minutes.",
      "Add shrimp or tofu and cook until shrimp turns pink (about 3-4 minutes) or tofu is heated through.",
      "Remove from heat and stir in lime juice.",
      "Remove lemongrass and ginger pieces.",
      "Serve hot, garnished with fresh cilantro and green onions.",
    ],
    authorId: "user_4",
    authorName: "Suki Tanaka",
  },
  {
    id: "6",
    title: "Berry Smoothie Bowl",
    description: "A nutritious and colorful smoothie bowl topped with fresh fruits and granola.",
    image: "/placeholder.svg?height=300&width=400",
    rating: 4.4,
    prepTime: "10 mins",
    cookTime: "0 mins",
    tags: ["Breakfast", "Healthy", "Vegan", "Smoothie"],
    ingredients: [
      "1 cup frozen mixed berries",
      "1 frozen banana",
      "1/2 cup almond milk (or any milk of choice)",
      "1 tablespoon honey or maple syrup (optional)",
      "1 tablespoon chia seeds",
      "Toppings: fresh berries, sliced banana, granola, coconut flakes",
    ],
    instructions: [
      "Add frozen berries, banana, and almond milk to a blender.",
      "Blend until smooth, adding more milk if needed to reach desired consistency.",
      "Add honey or maple syrup if desired and blend briefly.",
      "Pour into a bowl.",
      "Top with fresh berries, sliced banana, granola, coconut flakes, and chia seeds.",
      "Serve immediately.",
    ],
    authorId: "user_3",
    authorName: "Emma Wilson",
  },
]

